### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by M-I-Kessler** [SacriPudding/bdsx-phapi-player#1]
`[BDSX-Plugins] Loading @bdsx/phapi-player (6/8)
[BDSX] PdbReader: Cache not found, Player::getCertificate
[BDSX] PdbReader: Search Symbols...
Player::getCertificate not found
[BDSX-Plugins] Failed to load @bdsx/phapi-player
TypeError: arg1, expected=*Pointer, actual=undefined
   at js (bdsx\bdsx\makefunc.ts:373:60)
   at ProcHacker.prototype.js (bdsx\bdsx\prochacker.ts:371:9)
   at Anonymous function (bdsx\node_modules\@bdsx\phapi-player\src\functions.ts:87:14)
   at require (internal/modules/cjs/helpers.js:22:7)
   at Anonymous function (bdsx\node_modules\@bdsx\phapi-player\index.ts:2:1)
`

**Comment by SacriGrape** [comment]
Pretty confident I fixed this, though I have no way to test if the change I made actually works
